export interface ContribuyenteIndividual {
  apellidoCasada: string;
  cedulaNumero: string;
  cedulaRegistro: number;
  codComunidadLinguistica: number;
  codPoblacionLinguistica: number;
  codigoEstadoCivil: number;
  codigoNacionalidad: number;
  codigoPais: number;
  cui: number;
  fechaAdiciono: Date;
  fechaEmisionDpi: Date;
  fechaFallecimiento: Date;
  fechaModifico: Date;
  fechaNacimiento: Date;
  fechaVencimientoDpi: Date;
  importador: string;
  nit: string;
  numeroIgss: number;
  pasaporte: string;
  primerApellido: string;
  primerNombre: string;
  proveedorEstado: string;
  proveedorSat: string;
  segundoApellido: string;
  segundoNombre: string;
  sexo: number;
  tipoNit: number;
  usuarioAdiciono: string;
  usuarioModifico: string
}